GET http://localhost:3000/api/guitars
###
GET http://localhost:3000/api/guitars/96
###
POST http://localhost:3000/api/guitars
Content-Type: application/json

{
    "brand": "Ibanez",
    "model": "flying V",
    "color": "white"
}

###
PUT http://localhost:3000/api/guitars/63


{
    "brand": "Fender",
    "model": "Stratocaster",
    "color": "Red"
}


###
DELETE http://localhost:3000/api/guitars/96


