GET http://localhost:3000/api/guitars
###
GET http://localhost:3000/api/guitars/96
###
POST http://localhost:3000/api/guitars
Content-Type: application/json

{
    "brand": "Gibson",
    "model": "SG",
    "color": "Cherry"
}

###
PUT http://localhost:3000/api/guitars/65
Content-Type: application/json

{
    "brand": "Fender",
    "model": "Stratocaster",
    "color": "Maple"
}


###
DELETE http://localhost:3000/api/guitars/96


